<a href="https://colab.research.google.com/github/HamzahMadi4105/MachineLearning/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import torch.optim as optim
from matplotlib import pyplot as plt

Problem 1

In [210]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [211]:
def model(w2,t_u,w1,b):
    return w2* t_u**2+w1*t_u+b

In [212]:
def loss_fn(t_p, t_c):
  square_diff = (t_p - t_c)**2
  return square_diff.mean();

In [213]:
w1 = torch.ones((), requires_grad=True)
w2 = torch.ones((), requires_grad=True)
b = torch.zeros((), requires_grad=True)

In [214]:
n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices


(tensor([7, 3, 6, 1, 0, 4, 8, 9, 2]), tensor([10,  5]))

In [215]:
train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]

val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]

train_t_un = 0.1 * train_t_u
val_t_un = 0.1 * val_t_u

In [216]:
def training_loop(n_epochs, optimizer, params, train_t_u, val_t_u, train_t_c, val_t_c):


    for epoch in range(1, n_epochs + 1):
        train_t_p = model(train_t_u, *params)
        train_loss = loss_fn(train_t_p, train_t_c)

        val_t_p = model(val_t_u, *params)
        val_loss = loss_fn(val_t_p, val_t_c)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch <=2 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

    return params


In [217]:
t_un = 0.1 * t_u

In [218]:
def learning_rates(learning_rates, optimizer_func,epochs ):
    for lr in learning_rates:
        params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
        optimizer = optimizer_func([params], lr=lr)
        trained_params = training_loop(
            n_epochs=epochs,
            optimizer=optimizer,
            params=params,
            train_t_u=train_t_un,
            val_t_u=val_t_un,
            train_t_c=train_t_c,
            val_t_c=val_t_c
        )
learning_rates([0.1, 0.01, 0.001, 0.0001, 0.0000001], optim.SGD, 5000)

Epoch 1, Training loss 66.7033, Validation loss 88.8188
Epoch 2, Training loss 1011034.4375, Validation loss 1263455.0000
Epoch 500, Training loss nan, Validation loss nan
Epoch 1000, Training loss nan, Validation loss nan
Epoch 1500, Training loss nan, Validation loss nan
Epoch 2000, Training loss nan, Validation loss nan
Epoch 2500, Training loss nan, Validation loss nan
Epoch 3000, Training loss nan, Validation loss nan
Epoch 3500, Training loss nan, Validation loss nan
Epoch 4000, Training loss nan, Validation loss nan
Epoch 4500, Training loss nan, Validation loss nan
Epoch 5000, Training loss nan, Validation loss nan
Epoch 1, Training loss 66.7033, Validation loss 88.8188
Epoch 2, Training loss 356.4128, Validation loss 334.1031
Epoch 500, Training loss nan, Validation loss nan
Epoch 1000, Training loss nan, Validation loss nan
Epoch 1500, Training loss nan, Validation loss nan
Epoch 2000, Training loss nan, Validation loss nan
Epoch 2500, Training loss nan, Validation loss nan
E

In [219]:
learning_rates([0.1, 0.01, 0.001, 0.0001], optim.Adam,5000)

Epoch 1, Training loss 66.7033, Validation loss 88.8188
Epoch 2, Training loss 53.8914, Validation loss 65.4340
Epoch 500, Training loss 3.1536, Validation loss 2.1562
Epoch 1000, Training loss 3.1536, Validation loss 2.1562
Epoch 1500, Training loss 3.1536, Validation loss 2.1562
Epoch 2000, Training loss 3.1536, Validation loss 2.1562
Epoch 2500, Training loss 3.1536, Validation loss 2.1562
Epoch 3000, Training loss 3.1536, Validation loss 2.1562
Epoch 3500, Training loss 3.1536, Validation loss 2.1562
Epoch 4000, Training loss 3.1536, Validation loss 2.1571
Epoch 4500, Training loss 3.1536, Validation loss 2.1553
Epoch 5000, Training loss 3.1537, Validation loss 2.1444
Epoch 1, Training loss 66.7033, Validation loss 88.8188
Epoch 2, Training loss 65.3019, Validation loss 86.3648
Epoch 500, Training loss 7.9687, Validation loss 7.2711
Epoch 1000, Training loss 3.1694, Validation loss 2.3611
Epoch 1500, Training loss 3.1536, Validation loss 2.1577
Epoch 2000, Training loss 3.1536, Val

Problem 2

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [13]:
file_path = '/content/drive/My Drive/Courses/Intro-to-ML/Datasets/Housing.csv'
housing = pd.DataFrame(pd.read_csv(file_path))
housing.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [14]:
# List of variables to map

varlist =  ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

# Defining the map function
def binary_map(x):
    return x.map({'yes': 1, 'no': 0})

# Applying the function to the housing list
housing[varlist] = housing[varlist].apply(binary_map)
housing.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

  furnishingstatus  
0        furnished  
1        furnished  
2   semi-furnished  
3        furnished  
4        furnished

In [28]:
from sklearn.model_selection import train_test_split

# We specify this so that the train and test data set always have the same rows, respectively
np.random.seed(0)
df_train, df_test = train_test_split(housing, train_size = 0.8, test_size = 0.2, random_state = 100)

In [29]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# Apply scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking','price']

df_train[num_vars] = scaler.fit_transform(df_train[num_vars])
df_train.head()

price      area  bedrooms  bathrooms   stories  mainroad  guestroom  \
22   0.596970  0.432609       0.4   0.000000  0.000000         1          1   
41   0.527273  0.314954       0.4   0.333333  1.000000         1          0   
91   0.404242  0.342105       0.2   0.000000  0.000000         1          1   
118  0.363636  0.319131       0.4   0.000000  0.000000         1          0   
472  0.109091  0.124896       0.6   0.000000  0.333333         1          0   

     basement  hotwaterheating  airconditioning   parking  prefarea  \
22          1                0                1  0.333333         0   
41          0                0                1  0.000000         1   
91          1                0                0  0.666667         1   
118         1                0                1  0.000000         1   
472         0                0                0  1.000000         0   

    furnishingstatus  
22         furnished  
41         furnished  
91         furnished  
118        furnished  
472   semi-furnished

In [92]:
# Separate features and labels
y_train= df_train[num_vars].values[:, 5]  # get input values from first column -- X is a list here
x_train = df_train[num_vars].values[:, (0,1,2,3,4)]  # get output values from second column -- Y is the list here
m = len(y_train)  # Number of training examples
n = len(x_train)  # Number of training examples

In [93]:
y_train = torch.tensor(y_train)
x_train = torch.tensor(x_train)

In [118]:
def model2(parmas,x_train):  #Linear model = y_train = return
    w4, w3, w2, w1, w0, b = params
    return w4*x_train[:,4]+w3*x_train[:,3]+w2*x_train[:,2] +w1* x_train[:,1]+w0*x_train[:,0]+b

In [119]:
def loss_fn2(t_p, y_train):
  square_diff = (t_p - y_train)**2
  return square_diff.mean();

In [120]:
w1 = torch.ones((), requires_grad=True)
w2 = torch.ones((), requires_grad=True)
w3 = torch.ones((), requires_grad=True)
w4 = torch.ones((), requires_grad=True)
#w5 = torch.ones((), requires_grad=True)
b = torch.zeros((), requires_grad=True)

In [121]:
n_samples = x_train.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([100, 125, 202, 252, 272,  93, 421, 402, 170, 296, 345, 405, 110, 348,
          98, 376, 388, 403, 153, 301,  51, 271, 160,  69,  88, 242, 279, 434,
         299, 222, 357, 399, 373, 291,  29,  47, 166, 295, 167, 161,  19, 340,
         362, 142,  79,  40, 408, 308, 227, 429, 391, 277, 315, 121, 339, 283,
         256, 323, 302,  75, 328,  36, 215,  30, 285, 224,   6, 106, 395,  33,
         253, 264, 390, 337, 270,  24, 425, 365, 267, 396, 330, 245, 394, 239,
         111, 363, 243, 338, 133, 190, 162, 213, 360, 107, 136, 154, 247, 251,
         297,  68,  10,  54, 355, 118, 335, 369, 159, 139, 380, 200, 307, 179,
         417,  61,  66, 268,  62, 411, 259,  28, 149,  44, 313,  21, 336,  57,
         115, 420, 325, 137, 174, 326, 129, 424, 423, 281, 155, 143, 305, 230,
         406, 311, 105, 312,  52,   2,  99, 212, 132, 286, 196, 209, 397, 126,
         173,  17,  20, 269,  89, 366, 158, 124,  80, 341, 430, 418,   0, 432,
         389, 250, 379, 112, 317, 210, 404, 175,  56

In [122]:
train_x = x_train[train_indices]
train_y = y_train[train_indices]

val_x = x_train[val_indices]
val_y= y_train[val_indices]

In [123]:
print("train_x shape:", train_x.shape)
print("train_y shape:", train_y.shape)
print("val_x shape:", val_x.shape)
print("val_y shape:", val_y.shape)

train_x shape: torch.Size([349, 5])
train_y shape: torch.Size([349])
val_x shape: torch.Size([87, 5])
val_y shape: torch.Size([87])


In [126]:
def training_loop(n_epochs, optimizer, params, train_x, val_x, train_y, val_y):
    for epoch in range(1, n_epochs + 1):

        train_t_p = model2(params, train_x)
        train_loss = loss_fn2(train_t_p, train_y)
        with torch.no_grad():

          val_t_p = model2(params, val_x)
          val_loss = loss_fn2(val_t_p, val_y)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch <= 2 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

    return params

SGD Training

In [144]:
print("Learning rate 0.01:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.01
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.01:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 1.1490, Validation loss 1.2661
Epoch 500, Training loss 0.0499, Validation loss 0.0609
Epoch 1000, Training loss 0.0233, Validation loss 0.0271
Epoch 1500, Training loss 0.0166, Validation loss 0.0174
Epoch 2000, Training loss 0.0144, Validation loss 0.0140
Epoch 2500, Training loss 0.0135, Validation loss 0.0125
Epoch 3000, Training loss 0.0129, Validation loss 0.0118
Epoch 3500, Training loss 0.0126, Validation loss 0.0114
Epoch 4000, Training loss 0.0124, Validation loss 0.0112
Epoch 4500, Training loss 0.0122, Validation loss 0.0110
Epoch 5000, Training loss 0.0121, Validation loss 0.0109


tensor([0.1009, 0.1175, 0.2902, 0.1951, 0.4523, 0.0024], requires_grad=True)

In [131]:
print("Learning rate 0.1:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.1
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.1:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 0.7116, Validation loss 0.8055
Epoch 500, Training loss 0.0121, Validation loss 0.0109
Epoch 1000, Training loss 0.0118, Validation loss 0.0106
Epoch 1500, Training loss 0.0117, Validation loss 0.0106
Epoch 2000, Training loss 0.0117, Validation loss 0.0105
Epoch 2500, Training loss 0.0117, Validation loss 0.0105
Epoch 3000, Training loss 0.0117, Validation loss 0.0105
Epoch 3500, Training loss 0.0117, Validation loss 0.0105
Epoch 4000, Training loss 0.0117, Validation loss 0.0105
Epoch 4500, Training loss 0.0117, Validation loss 0.0105
Epoch 5000, Training loss 0.0117, Validation loss 0.0105


tensor([0.1147, 0.1481, 0.3100, 0.0553, 0.4101, 0.0535], requires_grad=True)

In [133]:
print("Learning rate 0.001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.001
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.001:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 1.1996, Validation loss 1.3191
Epoch 500, Training loss 0.2150, Validation loss 0.2639
Epoch 1000, Training loss 0.1333, Validation loss 0.1630
Epoch 1500, Training loss 0.1133, Validation loss 0.1366
Epoch 2000, Training loss 0.0994, Validation loss 0.1196
Epoch 2500, Training loss 0.0877, Validation loss 0.1058
Epoch 3000, Training loss 0.0777, Validation loss 0.0940
Epoch 3500, Training loss 0.0691, Validation loss 0.0839
Epoch 4000, Training loss 0.0617, Validation loss 0.0751
Epoch 4500, Training loss 0.0553, Validation loss 0.0675
Epoch 5000, Training loss 0.0499, Validation loss 0.0608


tensor([ 0.4083,  0.3366,  0.6593,  0.5784,  0.7084, -0.3968],
       requires_grad=True)

In [135]:
print("Learning rate 0.0001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.0001
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.0001:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 1.2048, Validation loss 1.3245
Epoch 500, Training loss 0.9556, Validation loss 1.0632
Epoch 1000, Training loss 0.7646, Validation loss 0.8616
Epoch 1500, Training loss 0.6188, Validation loss 0.7066
Epoch 2000, Training loss 0.5074, Validation loss 0.5871
Epoch 2500, Training loss 0.4221, Validation loss 0.4949
Epoch 3000, Training loss 0.3568, Validation loss 0.4234
Epoch 3500, Training loss 0.3066, Validation loss 0.3678
Epoch 4000, Training loss 0.2679, Validation loss 0.3245
Epoch 4500, Training loss 0.2380, Validation loss 0.2905
Epoch 5000, Training loss 0.2148, Validation loss 0.2637


tensor([ 0.8058,  0.7669,  0.9072,  0.7645,  0.8533, -0.5041],
       requires_grad=True)

ADAM training

In [136]:
print("Learning rate 0.01:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.01
optimizer =optim.Adam([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.01:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 1.1564, Validation loss 1.2734
Epoch 500, Training loss 0.0138, Validation loss 0.0142
Epoch 1000, Training loss 0.0119, Validation loss 0.0110
Epoch 1500, Training loss 0.0118, Validation loss 0.0106
Epoch 2000, Training loss 0.0117, Validation loss 0.0105
Epoch 2500, Training loss 0.0117, Validation loss 0.0105
Epoch 3000, Training loss 0.0117, Validation loss 0.0105
Epoch 3500, Training loss 0.0117, Validation loss 0.0105
Epoch 4000, Training loss 0.0117, Validation loss 0.0105
Epoch 4500, Training loss 0.0117, Validation loss 0.0105
Epoch 5000, Training loss 0.0117, Validation loss 0.0105


tensor([0.1147, 0.1481, 0.3100, 0.0553, 0.4101, 0.0535], requires_grad=True)

In [137]:
print("Learning rate 0.001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.001
optimizer =optim.Adam([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.001:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 1.2004, Validation loss 1.3198
Epoch 500, Training loss 0.1216, Validation loss 0.1547
Epoch 1000, Training loss 0.0502, Validation loss 0.0628
Epoch 1500, Training loss 0.0340, Validation loss 0.0426
Epoch 2000, Training loss 0.0234, Validation loss 0.0292
Epoch 2500, Training loss 0.0177, Validation loss 0.0213
Epoch 3000, Training loss 0.0152, Validation loss 0.0170
Epoch 3500, Training loss 0.0139, Validation loss 0.0146
Epoch 4000, Training loss 0.0132, Validation loss 0.0132
Epoch 4500, Training loss 0.0126, Validation loss 0.0122
Epoch 5000, Training loss 0.0122, Validation loss 0.0115


tensor([ 0.1103,  0.1220,  0.2627,  0.2299,  0.4298, -0.0075],
       requires_grad=True)

In [138]:
print("Learning rate 0.1:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.1
optimizer =optim.Adam([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.1:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 0.7647, Validation loss 0.8581
Epoch 500, Training loss 0.0117, Validation loss 0.0105
Epoch 1000, Training loss 0.0117, Validation loss 0.0105
Epoch 1500, Training loss 0.0117, Validation loss 0.0105
Epoch 2000, Training loss 0.0117, Validation loss 0.0105
Epoch 2500, Training loss 0.0117, Validation loss 0.0105
Epoch 3000, Training loss 0.0117, Validation loss 0.0105
Epoch 3500, Training loss 0.0117, Validation loss 0.0105
Epoch 4000, Training loss 0.0117, Validation loss 0.0105
Epoch 4500, Training loss 0.0117, Validation loss 0.0105
Epoch 5000, Training loss 0.0117, Validation loss 0.0105


tensor([0.1147, 0.1481, 0.3100, 0.0553, 0.4101, 0.0535], requires_grad=True)

In [140]:
print("Learning rate 0.0001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.0001
optimizer =optim.Adam([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x=train_x,
              val_x=val_x,
              train_y=train_y,
              val_y=val_y
          )

Learning rate 0.0001:
Epoch 1, Training loss 1.2053, Validation loss 1.3251
Epoch 2, Training loss 1.2048, Validation loss 1.3245
Epoch 500, Training loss 0.9774, Validation loss 1.0840
Epoch 1000, Training loss 0.7841, Validation loss 0.8787
Epoch 1500, Training loss 0.6215, Validation loss 0.7050
Epoch 2000, Training loss 0.4862, Validation loss 0.5594
Epoch 2500, Training loss 0.3750, Validation loss 0.4386
Epoch 3000, Training loss 0.2853, Validation loss 0.3402
Epoch 3500, Training loss 0.2148, Validation loss 0.2617
Epoch 4000, Training loss 0.1611, Validation loss 0.2008
Epoch 4500, Training loss 0.1221, Validation loss 0.1553
Epoch 5000, Training loss 0.0951, Validation loss 0.1227


tensor([ 0.5970,  0.5971,  0.5928,  0.6162,  0.6163, -0.3688],
       requires_grad=True)

In [171]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# Apply scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ['price','area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking','prefarea']

df_train[num_vars] = scaler.fit_transform(df_train[num_vars])
df_train.head()

price      area  bedrooms  bathrooms   stories  mainroad  guestroom  \
22   0.596970  0.432609       0.4   0.000000  0.000000       1.0        1.0   
41   0.527273  0.314954       0.4   0.333333  1.000000       1.0        0.0   
91   0.404242  0.342105       0.2   0.000000  0.000000       1.0        1.0   
118  0.363636  0.319131       0.4   0.000000  0.000000       1.0        0.0   
472  0.109091  0.124896       0.6   0.000000  0.333333       1.0        0.0   

     basement  hotwaterheating  airconditioning   parking  prefarea  \
22        1.0              0.0              1.0  0.333333       0.0   
41        0.0              0.0              1.0  0.000000       1.0   
91        1.0              0.0              0.0  0.666667       1.0   
118       1.0              0.0              1.0  0.000000       1.0   
472       0.0              0.0              0.0  1.000000       0.0   

    furnishingstatus  
22         furnished  
41         furnished  
91         furnished  
118        furnished  
472   semi-furnished

In [175]:
# Separate features and labels
y_train3= df_train[num_vars].values[:, 0]  # get input values from first column -- y is a list here
x_train3 = df_train[num_vars].values[:, 1:13]  # get output values from second column -- x is the list here
m = len(y_train)  # Number of training examples
n = len(x_train)  # Number of training examples

In [176]:
y_train3 = torch.tensor(y_train3)
x_train3 = torch.tensor(x_train3)

In [177]:
def model3(parmas,x_train3):  #Linear model = y_train = return
    w10,w9,w8,w7,w6,w5, w4, w3, w2, w1, w0, b = params
    return w10*x_train3[:,10] + w9*x_train3[:,9] + w8*x_train3[:,8] + w7*x_train3[:,7] + w6*x_train3[:,6] + w5*x_train3[:,5] + w4*x_train3[:,4] + w3*x_train3[:,3] + w2*x_train3[:,2] + w1*x_train3[:,1] + w0*x_train3[:,0] + b

In [178]:
def loss_fn3(t_p, y_train3):
  square_diff = (t_p - y_train3)**2
  return square_diff.mean();

In [179]:
w1 = torch.ones((), requires_grad=True)
w2 = torch.ones((), requires_grad=True)
w3 = torch.ones((), requires_grad=True)
w4 = torch.ones((), requires_grad=True)
w5 = torch.ones((), requires_grad=True)
w6 = torch.ones((), requires_grad=True)
w7 = torch.ones((), requires_grad=True)
w8 = torch.ones((), requires_grad=True)
w9 = torch.ones((), requires_grad=True)
w10 = torch.ones((), requires_grad=True)
b = torch.zeros((), requires_grad=True)

In [180]:
n_samples = x_train3.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([325, 250, 224, 408, 390, 364,  21, 241,  69,  34, 351, 189,  99, 176,
          19,  44, 149, 431, 158, 142, 356,  20, 147, 423,  81, 400,  59, 343,
         401, 275, 169, 227,  71, 313, 308, 217, 303, 221, 235, 211,  80, 283,
         264, 164, 335, 392, 426, 251,  64, 243, 248, 339, 144,  83, 410,  22,
         188,   0, 324, 116,   2, 338, 222, 181, 429, 381, 334, 298, 115, 130,
         236, 197,  16, 288, 333, 395, 306,  66,  40, 378, 226, 357, 389, 118,
         204,  50,  67, 413, 278, 307, 321, 388,  36, 407, 404, 369, 411, 133,
         391, 385, 405, 361, 117, 416,  45, 101, 258, 272, 134, 141,  97,  29,
          12, 421,  42, 119, 209, 200, 347, 387, 234,  62, 245, 203, 139,  63,
         320, 263,   5, 230,  87, 177, 380, 153, 394, 362, 268,  90,  18, 239,
           4, 277, 428, 155, 330, 266,  56, 427, 344, 237,  72, 109, 229, 261,
         201, 350, 425, 412, 107,  85,  33, 205, 160, 184, 433, 409, 165, 262,
         223,   1, 185, 296,  37, 112, 173, 135, 267

In [181]:
train_x3 = x_train3[train_indices]
train_y3 = y_train3[train_indices]

val_x3 = x_train3[val_indices]
val_y3= y_train3[val_indices]

In [221]:
def training_loop(n_epochs, optimizer, params, train_x3, val_x3, train_y3, val_y3):
    for epoch in range(1, n_epochs + 1):

        train_t_p3 = model3(params, train_x3)
        train_loss3 = loss_fn3(train_t_p3, train_y3)
        with torch.no_grad():

          val_t_p3 = model3(params, val_x3)
          val_loss3 = loss_fn3(val_t_p3, val_y3)

        optimizer.zero_grad()
        train_loss3.backward()
        optimizer.step()

        if epoch <= 2 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss3.item():.4f},"
                  f" Validation loss {val_loss3.item():.4f}")

    return params

SGD

In [184]:
print("Learning rate 0.01:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.01
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.01:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 9.7997, Validation loss 8.6611
Epoch 500, Training loss 0.0663, Validation loss 0.0519
Epoch 1000, Training loss 0.0242, Validation loss 0.0181
Epoch 1500, Training loss 0.0144, Validation loss 0.0118
Epoch 2000, Training loss 0.0114, Validation loss 0.0100
Epoch 2500, Training loss 0.0103, Validation loss 0.0093
Epoch 3000, Training loss 0.0098, Validation loss 0.0089
Epoch 3500, Training loss 0.0096, Validation loss 0.0086
Epoch 4000, Training loss 0.0094, Validation loss 0.0084
Epoch 4500, Training loss 0.0093, Validation loss 0.0082
Epoch 5000, Training loss 0.0092, Validation loss 0.0081


tensor([ 0.0512,  0.0389,  0.0777,  0.0805,  0.0271,  0.0230,  0.0641,  0.0685,
         0.2756,  0.1741,  0.3403, -0.0485], requires_grad=True)

In [185]:
print("Learning rate 0.1:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.1
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.1:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 3.0315, Validation loss 2.5939
Epoch 500, Training loss 0.0092, Validation loss 0.0081
Epoch 1000, Training loss 0.0090, Validation loss 0.0076
Epoch 1500, Training loss 0.0089, Validation loss 0.0075
Epoch 2000, Training loss 0.0089, Validation loss 0.0075
Epoch 2500, Training loss 0.0089, Validation loss 0.0075
Epoch 3000, Training loss 0.0089, Validation loss 0.0075
Epoch 3500, Training loss 0.0089, Validation loss 0.0075
Epoch 4000, Training loss 0.0089, Validation loss 0.0075
Epoch 4500, Training loss 0.0089, Validation loss 0.0075
Epoch 5000, Training loss 0.0089, Validation loss 0.0075


tensor([ 0.0537,  0.0559,  0.0769,  0.0807,  0.0307,  0.0267,  0.0563,  0.0969,
         0.2962,  0.0576,  0.2983, -0.0021], requires_grad=True)

In [186]:
print("Learning rate 0.001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.001
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.001:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 10.7117, Validation loss 9.4873
Epoch 500, Training loss 0.4980, Validation loss 0.4457
Epoch 1000, Training loss 0.3222, Validation loss 0.3064
Epoch 1500, Training loss 0.2450, Validation loss 0.2290
Epoch 2000, Training loss 0.1915, Validation loss 0.1743
Epoch 2500, Training loss 0.1534, Validation loss 0.1357
Epoch 3000, Training loss 0.1256, Validation loss 0.1079
Epoch 3500, Training loss 0.1048, Validation loss 0.0876
Epoch 4000, Training loss 0.0888, Validation loss 0.0724
Epoch 4500, Training loss 0.0763, Validation loss 0.0608
Epoch 5000, Training loss 0.0663, Validation loss 0.0518


tensor([ 0.1075,  0.3099,  0.0854,  0.5663,  0.0595,  0.1158,  0.1406,  0.3035,
         0.5860,  0.4661,  0.5800, -0.5516], requires_grad=True)

In [222]:
print("Learning rate 0.0001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.0001
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.0001:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 10.8053, Validation loss 9.5721
Epoch 500, Training loss 6.7312, Validation loss 5.8925
Epoch 1000, Training loss 4.2614, Validation loss 3.6829
Epoch 1500, Training loss 2.7690, Validation loss 2.3638
Epoch 2000, Training loss 1.8649, Validation loss 1.5765
Epoch 2500, Training loss 1.3147, Validation loss 1.1064
Epoch 3000, Training loss 0.9777, Validation loss 0.8248
Epoch 3500, Training loss 0.7692, Validation loss 0.6551
Epoch 4000, Training loss 0.6381, Validation loss 0.5517
Epoch 4500, Training loss 0.5538, Validation loss 0.4872
Epoch 5000, Training loss 0.4979, Validation loss 0.4456


tensor([ 0.5612,  0.6494,  0.4898,  0.8919,  0.4096,  0.6339,  0.0261,  0.6274,
         0.8381,  0.5497,  0.7053, -1.0106], requires_grad=True)

Adam

In [223]:
print("Learning rate 0.1:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.1
optimizer =optim.Adam([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.1:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 8.0706, Validation loss 7.1208
Epoch 500, Training loss 0.0089, Validation loss 0.0075
Epoch 1000, Training loss 0.0089, Validation loss 0.0075
Epoch 1500, Training loss 0.0089, Validation loss 0.0075
Epoch 2000, Training loss 0.0089, Validation loss 0.0075
Epoch 2500, Training loss 0.0089, Validation loss 0.0075
Epoch 3000, Training loss 0.0089, Validation loss 0.0075
Epoch 3500, Training loss 0.0089, Validation loss 0.0075
Epoch 4000, Training loss 0.0089, Validation loss 0.0075
Epoch 4500, Training loss 0.0089, Validation loss 0.0075
Epoch 5000, Training loss 0.0089, Validation loss 0.0075


tensor([ 0.0537,  0.0559,  0.0769,  0.0807,  0.0307,  0.0267,  0.0563,  0.0969,
         0.2962,  0.0576,  0.2983, -0.0021], requires_grad=True)

In [224]:
print("Learning rate 0.01:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.01
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.01:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 9.7997, Validation loss 8.6611
Epoch 500, Training loss 0.0663, Validation loss 0.0519
Epoch 1000, Training loss 0.0242, Validation loss 0.0181
Epoch 1500, Training loss 0.0144, Validation loss 0.0118
Epoch 2000, Training loss 0.0114, Validation loss 0.0100
Epoch 2500, Training loss 0.0103, Validation loss 0.0093
Epoch 3000, Training loss 0.0098, Validation loss 0.0089
Epoch 3500, Training loss 0.0096, Validation loss 0.0086
Epoch 4000, Training loss 0.0094, Validation loss 0.0084
Epoch 4500, Training loss 0.0093, Validation loss 0.0082
Epoch 5000, Training loss 0.0092, Validation loss 0.0081


tensor([ 0.0512,  0.0389,  0.0777,  0.0805,  0.0271,  0.0230,  0.0641,  0.0685,
         0.2756,  0.1741,  0.3403, -0.0485], requires_grad=True)

In [225]:
print("Learning rate 0.001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.001
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.001:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 10.7117, Validation loss 9.4873
Epoch 500, Training loss 0.4980, Validation loss 0.4457
Epoch 1000, Training loss 0.3222, Validation loss 0.3064
Epoch 1500, Training loss 0.2450, Validation loss 0.2290
Epoch 2000, Training loss 0.1915, Validation loss 0.1743
Epoch 2500, Training loss 0.1534, Validation loss 0.1357
Epoch 3000, Training loss 0.1256, Validation loss 0.1079
Epoch 3500, Training loss 0.1048, Validation loss 0.0876
Epoch 4000, Training loss 0.0888, Validation loss 0.0724
Epoch 4500, Training loss 0.0763, Validation loss 0.0608
Epoch 5000, Training loss 0.0663, Validation loss 0.0518


tensor([ 0.1075,  0.3099,  0.0854,  0.5663,  0.0595,  0.1158,  0.1406,  0.3035,
         0.5860,  0.4661,  0.5800, -0.5516], requires_grad=True)

In [228]:
print("Learning rate 0.0001:")
params = torch.tensor([1.0, 1.0, 1.0, 1.0,1.0,1.0, 1.0, 1.0, 1.0,1.0,1.0, 0.0], requires_grad=True)
learning_rates = 0.0001
optimizer =optim.SGD([params], lr=learning_rates)
training_loop(
              n_epochs=5000,
              optimizer=optimizer,
              params=params,
              train_x3=train_x3,
              val_x3=val_x3,
              train_y3=train_y3,
              val_y3=val_y3
          )

Learning rate 0.0001:
Epoch 1, Training loss 10.8157, Validation loss 9.5816
Epoch 2, Training loss 10.8053, Validation loss 9.5721
Epoch 500, Training loss 6.7312, Validation loss 5.8925
Epoch 1000, Training loss 4.2614, Validation loss 3.6829
Epoch 1500, Training loss 2.7690, Validation loss 2.3638
Epoch 2000, Training loss 1.8649, Validation loss 1.5765
Epoch 2500, Training loss 1.3147, Validation loss 1.1064
Epoch 3000, Training loss 0.9777, Validation loss 0.8248
Epoch 3500, Training loss 0.7692, Validation loss 0.6551
Epoch 4000, Training loss 0.6381, Validation loss 0.5517
Epoch 4500, Training loss 0.5538, Validation loss 0.4872
Epoch 5000, Training loss 0.4979, Validation loss 0.4456


tensor([ 0.5612,  0.6494,  0.4898,  0.8919,  0.4096,  0.6339,  0.0261,  0.6274,
         0.8381,  0.5497,  0.7053, -1.0106], requires_grad=True)